-- Keys for receiving self-assembly notifications from a trusted external mod.
create extension if not exists pgcrypto;

create table public.self_assembly_notification_keys (
  id bigint generated by default as identity primary key,
  key_hash text not null unique,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table public.self_assembly_notifications (
  id bigint generated by default as identity primary key,
  block_id bigint not null references public.blocks(id) on delete cascade,
  can_create boolean not null,
  message text,
  observed_at timestamptz not null default now(),
  received_at timestamptz not null default now()
);

alter table public.self_assembly_notification_keys enable row level security;
alter table public.self_assembly_notifications enable row level security;

create policy "Admins can manage notification keys"
  on public.self_assembly_notification_keys
  for all to authenticated
  using (exists (
    select 1 from public.user_roles
    where user_roles.user_id = auth.uid() and user_roles.role_id = 'admin'
  ))
  with check (exists (
    select 1 from public.user_roles
    where user_roles.user_id = auth.uid() and user_roles.role_id = 'admin'
  ));

create policy "Authenticated users can read notifications"
  on public.self_assembly_notifications
  for select to authenticated
  using (true);

create or replace function public.create_self_assembly_notification_key()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  raw_key text;
begin
  if not exists (
    select 1 from public.user_roles
    where user_roles.user_id = auth.uid() and user_roles.role_id = 'admin'
  ) then
    raise exception 'admin role required';
  end if;

  raw_key := 'sam_' || encode(gen_random_bytes(24), 'hex');
  insert into public.self_assembly_notification_keys (key_hash, created_by)
  values (encode(digest(raw_key, 'sha256'), 'hex'), auth.uid());
  return raw_key;
end;
$$;

create or replace function public.receive_self_assembly_notification(
  p_key text,
  p_block_id bigint,
  p_can_create boolean,
  p_message text default null,
  p_observed_at timestamptz default now()
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  key_id bigint;
  notification_id bigint;
begin
  select id into key_id
  from public.self_assembly_notification_keys
  where key_hash = encode(digest(p_key, 'sha256'), 'hex')
    and revoked_at is null;

  if key_id is null then
    raise exception 'invalid or revoked notification key';
  end if;

  insert into public.self_assembly_notifications (block_id, can_create, message, observed_at)
  values (p_block_id, p_can_create, p_message, p_observed_at)
  returning id into notification_id;

  return notification_id;
end;
$$;

revoke all on function public.create_self_assembly_notification_key() from public, anon, authenticated;
grant execute on function public.create_self_assembly_notification_key() to authenticated;
revoke all on function public.receive_self_assembly_notification(text, bigint, boolean, text, timestamptz)
  from public, anon, authenticated;
grant execute on function public.receive_self_assembly_notification(text, bigint, boolean, text, timestamptz)
  to anon, authenticated, service_role;

alter publication supabase_realtime add table public.self_assembly_notifications;
